# Generated by Django 2.1.7 on 2019-05-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date', '-created_at')},
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Date of the event (if empty, will show TBA)', null=True),
        ),
    ]
