# Generated by Django 2.1.7 on 2019-05-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If not active, it will not be shown on the list of available opportunities'),
        ),
    ]
