# Generated by Django 2.1.7 on 2019-05-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_auto_20190508_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunity',
            name='duration',
            field=models.CharField(choices=[('short_term', 'Short Term'), ('long_term', 'Long Term')], default='short_term', max_length=20),
        ),
    ]
