# Generated by Django 2.1.7 on 2019-05-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_auto_20190511_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteeropportunity',
            options={'verbose_name': 'Volunteering opportunity', 'verbose_name_plural': 'Volunteering opportunities'},
        ),
    ]
