# Generated by Django 2.1.7 on 2019-05-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_auto_20190511_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteeropportunity',
            options={'ordering': ('-created_at',), 'verbose_name': 'Volunteering opportunity', 'verbose_name_plural': 'Volunteering opportunities'},
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='volunteer_profile',
            field=models.CharField(default='Example', help_text='What kind of volunteer we are looking for', max_length=500),
            preserve_default=False,
        ),
    ]
