# Generated by Django 2.1.7 on 2019-05-11 18:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0008_auto_20190511_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='What the volunteer will need to do (What will you be doing?)'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='reason',
            field=models.CharField(help_text='Why this is important (Why will you want to do this?)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='rewards',
            field=models.CharField(help_text='What the volunteer will get for doing this (What will you get from this opportunity?)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='volunteer_profile',
            field=models.CharField(help_text='What kind of volunteer we are looking for (Who are we looking for?)', max_length=500),
        ),
    ]
