# Generated by Django 2.1.7 on 2019-05-11 18:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0009_auto_20190511_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='reason',
            field=ckeditor.fields.RichTextField(help_text='Why this is important (Why will you want to do this?)', null=True),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='rewards',
            field=ckeditor.fields.RichTextField(help_text='What the volunteer will get for doing this (What will you get from this opportunity?)', null=True),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='volunteer_profile',
            field=ckeditor.fields.RichTextField(help_text='What kind of volunteer we are looking for (Who are we looking for?)'),
        ),
    ]
